### ISSUE TITLE
Conversion BF to points should still show points in GUI but output is BF polygons

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/DelftDashboard#143]
### Preliminary Checklist

- [x] I have searched the existing issues list for similar requests and found none. If you did find a similar requests, please add a comment to the existing requests instead of opening a new one.

### Kind of request

Changing existing functionality

### Enhancement Description

When the user does not want to convert the BF into points, the GUI displays points for each corner of the BF.

### Task list

- [ ] Display points at any time
- [ ] but change output according to user selection
