### ISSUE TITLE
Update Price year for max. potential damages

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/DelftDashboard#161]
### Preliminary Checklist

- [X] I have searched the existing issues list for similar requests and found none. If you did find a similar requests, please add a comment to the existing requests instead of opening a new one.

### Kind of request

Adding new functionality

### Enhancement Description

Currently the max. potential damages are not adjusted to the current price year (selected by user). 
This feature should be included

### Task list

- [ ] Get price year list 
- [ ] add button in GUI for the user to select a price year
- [ ] multiply max. potential damages with the multiplication factor
- [ ] save the price year for floodadapt
