### ISSUE TITLE
Quickbuild: Make sure user can update values after quickbuild

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/DelftDashboard#70]
**Current behavior**
When the user is doing quick build she/he can make changes in the model after and then rerun the model. However the model runs into issues and doesn't create the correct output. 

**Desired behavior**
The user can make changes afterwards and the output is correct. Also the model automatically re-runs when the user clicks ädd to model" and does not have to click again "create model"

**Tasks:**

- [x] Check if Quickbuild output is wrong when updating values and click "create model"
- [x] Include functionality like in "additional attributes"-tab that model automatically updates after click  "add to model"
- [x] ToDo: implement also for Max Potential Damages
