### ISSUE TITLE
Enable to add Additional Attributes after Quickbuild

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/DelftDashboard#71]
**Current behavior**

- The additional attributes tab is a subtab of Exposure. 
- The additional attributes cannot be updated/added after the quickbuild.

**Desired behavior**
As the additional attributes is not directly linked it exposure it should not be as a subtab. Similar to SVI/Equity it should be placed into a top tab and the user should be able to add additional attribues after the quickbuild eg aggregation zones

**Tasks**

- [x] Create a top tab for Additional Attributes
- [x] update function in fiat.py setup_aggregation_areas and remove the filter option (prevents from correct exectution)
- [x] Test Quick Build and additional attributes
- [ ] connect checkboxes in "Additional Attribute Ta" and "View Model tab" so that they check/uncheck together and both show hovering properties
- [x] create functionality to add additional attributes after quickbuild ( if model build : add to exposure_db with spatial joint)
